---
image:
  name: "nixos/nix"

variables:
  NIX_CONFIG: "experimental-features = nix-command flakes"

stages:
  - check
  - build

lint:
  stage: check
  # HACK: "build" the a single check to avoid running nix flake check (which requires too much RAM)
  script: nix build --print-build-logs .\#checks.x86_64-linux.pre-commit-check

secrets-check:
  stage: check
  script: nix run .#secrets-check -- secrets
