---
image:
  name: "nixos/nix"

variables:
  NIX_CONFIG: "experimental-features = nix-command flakes"

stages:
  - check
  - build

lint:
  stage: check
  script: nix fmt -- -c --quiet .

secrets-check:
  stage: check
  script: nix run .#secrets-check -- secrets
