---
image:
  name: "nixos/nix"

variables:
  NIX_CONFIG: "experimental-features = nix-command flakes"

stages:
  - check
  - build

lint:
  stage: check
  script: nix fmt -- -c --quiet .

build:
  stage: build
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$CACHE_PRIVATE_SSH_KEY" > ~/.ssh/id_ed25519
    - chmod 400 ~/.ssh/id_ed25519
    - echo "labs.cache.rnl.tecnico.ulisboa.pt ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILWWs0qnnsgKT78qjKo7LQ4BAoiL6N9bbxuBJswHqjrw" >> ~/.ssh/known_hosts

    - mkdir -p ~/.config/nix
    - echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
    - echo "substituters = https://proxy.cache.rnl.tecnico.ulisboa.pt https://labs.cache.rnl.tecnico.ulisboa.pt" >> ~/.config/nix/nix.conf
    - nix build .#nixosConfigurations.hagrid.config.system.build.toplevel
    - nix copy --to ssh://labs.cache.rnl.tecnico.ulisboa.pt result/
