---
image:
  name: "nixos/nix"

variables:
  NIX_CONFIG: "experimental-features = nix-command flakes"

stages:
  - check
  - build

lint:
  stage: check
  script:
    - nix fmt -- -c --quiet .
    - find . -type f -name "*.nix" -exec nix run nixpkgs#nil -- diagnostics {} \; > /tmp/nil.log
    - if [ -s /tmp/nil.log ]; then cat /tmp/nil.log && exit 1; fi

secrets-check:
  stage: check
  script: nix run .#secrets-check -- secrets
