[
  {
    "id": 7,
    "uid": "pxCqOS5Iz",
    "orgId": 1,
    "name": "Loki",
    "type": "loki",
    "typeName": "Loki",
    "typeLogoUrl": "/grafana/public/app/plugins/datasource/loki/img/loki_icon.svg",
    "access": "proxy",
    "url": "http://borg.rnl.tecnico.ulisboa.pt:13100",
    "user": "",
    "database": "",
    "basicAuth": false,
    "isDefault": false,
    "jsonData": {},
    "readOnly": false
  },
  {
    "id": 6,
    "uid": "y7lCbTU7z",
    "orgId": 1,
    "name": "MySQL",
    "type": "mysql",
    "typeName": "MySQL",
    "typeLogoUrl": "/grafana/public/app/plugins/datasource/mysql/img/mysql_logo.svg",
    "access": "proxy",
    "url": "db.rnl.tecnico.ulisboa.pt",
    "user": "opensessions",
    "database": "loginrnl",
    "basicAuth": false,
    "isDefault": false,
    "jsonData": {},
    "readOnly": false
  },
  {
    "id": 8,
    "uid": "d306f8d7-ec7c-418e-a6fa-c2106c3f23fd",
    "orgId": 1,
    "name": "MySQL Tardis",
    "type": "mysql",
    "typeName": "MySQL",
    "typeLogoUrl": "/grafana/public/app/plugins/datasource/mysql/img/mysql_logo.svg",
    "access": "proxy",
    "url": "localhost",
    "user": "grafana",
    "database": "",
    "basicAuth": false,
    "isDefault": false,
    "jsonData": {
      "connMaxLifetime": 14400,
      "database": "grafana",
      "maxIdleConns": 100,
      "maxIdleConnsAuto": true,
      "maxOpenConns": 100
    },
    "readOnly": false
  },
  {
    "id": 4,
    "uid": "PBFA97CFB590B2093",
    "orgId": 1,
    "name": "Prometheus",
    "type": "prometheus",
    "typeName": "Prometheus",
    "typeLogoUrl": "/grafana/public/app/plugins/datasource/prometheus/img/prometheus_logo.svg",
    "access": "proxy",
    "url": "http://localhost:9090",
    "user": "",
    "database": "",
    "basicAuth": false,
    "isDefault": true,
    "jsonData": {},
    "readOnly": true
  }
]
