apiVersion: 1
policies:
    - orgId: 1
      receiver: RNL Alertas (Mattermost)
      group_by:
        - grafana_folder
      routes:
        - receiver: RNL Alertas (Mattermost)
          group_by:
            - alertname
          object_matchers:
            - - team
              - =
              - rnl-infra
        - receiver: RNL Alertas (Mattermost)
          group_by:
            - '...'
          object_matchers:
            - - team
              - =
              - rnl-alerts
          repeat_interval: 9999w
        - receiver: RNL Alertas (Mattermost)
          group_by:
            - '...'
          object_matchers:
            - - team
              - =
              - rnl-nag
      group_interval: 1m
      repeat_interval: 12h
