{
 "title": "Virtual Machines",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team",
    "label": "Team",
    "query": {
     "query": "label_values(node_exporter_build_info{job=\"$job\", type=\"virtual\"}, team)"
    }
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(node_exporter_build_info{job=\"machines\", type=\"virtual\", team=~\"$team\"}, group)"
    }
   },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(node_exporter_build_info{job=\"machines\", type=\"virtual\", team=~\"$team\", group=~\"$group\"}, location)"
    }
   },
   {
    "name": "node",
    "label": "Instance(s)",
    "query": {
     "query": "label_values(node_exporter_build_info{job=\"machines\", type=\"virtual\", team=~\"$team\", group=~\"$group\", location=~\"$location\"}, instance)"
    }
   },
   {
    "name": "nic",
    "query": {
     "query": "label_values(node_network_receive_bytes_total{instance=\"$node\"}, device)"
    }
   },
   {
    "name": "disk_device",
    "query": {
     "query": "label_values(node_disk_read_bytes_total{instance=\"$node\", device!~\"nbd[0-9]+\"}, device)"
    }
   },
   { "name": "job", "query": "machines" }
  ]
 },
 "panels": [
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$node\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\"} - node_memory_SwapFree_bytes{instance=\"$node\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\"} )) * 100"
    }
   ]
  },
  {
   "title": "Root FS Usage",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_host_rev{job=\"machines\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Swap",
   "type": "stat",
   "description": "Total Swap",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$node\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"$node\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"$node\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  { "title": "Disk Space Usage", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 } },
  {
   "title": "Network Traffic Summary",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    {
     "format": "Bps",
     "label": "Bytes received(-) / transmitted(+)"
    }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$node\",device!~\"bond.*|lo\"}[5m]))",
     "legendFormat": "recv"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$node\",device!~\"bond.*|lo\"}[5m]))",
     "legendFormat": "trans"
    },
    {
     "expr": "sum(irate(node_network_receive_packets_total{instance=\"$node\",device!~\"bond.*|lo\"}[5m]))",
     "legendFormat": "recv packets"
    },
    {
     "expr": "sum(irate(node_network_transmit_packets_total{instance=\"$node\",device!~\"bond.*|lo\"}[5m]))",
     "legendFormat": "trans packets"
    }
   ]
  },
  {
   "title": "Disks I/O summary",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / written (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=\"$node\",device!~\"md.*\"}[5m]))",
     "legendFormat": "Read bytes"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=\"$node\",device!~\"md.*\"}[5m]))",
     "legendFormat": "Written bytes"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"} - node_memory_MemFree_bytes{instance=\"$node\"} - (node_memory_Cached_bytes{instance=\"$node\"} + node_memory_Buffers_bytes{instance=\"$node\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\"} + node_memory_Buffers_bytes{instance=\"$node\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\"} - node_memory_SwapFree_bytes{instance=\"$node\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\"}[45s]))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=\"$node\"}[45s]))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=\"$node\"}[45s]))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"$node\"}[45s]))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"$node\"}[45s]))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$node\"}[45s]))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "graph",
   "description": "Entropy available to random number generators",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "node_entropy_available_bits{instance=\"$node\"}",
     "legendFormat": "Available entropy"
    }
   ]
  },
  {
   "title": "Clock skew",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node_timex_offset_seconds{job=\"$job\",instance=~\"$node\"}",
     "legendFormat": "Clock skew"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{instance=\"$node\",phase=\"rtt\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "SSH Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ssh_success{job=\"ssh\", instance=~\"$node.*\", module=\"root\"}",
     "legendFormat": "public key"
    },
    {
     "expr": "ssh_success{job=\"ssh\", instance=~\"$node.*\", module=\"test\"}",
     "legendFormat": "password"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$node\", job=\"tcp\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "I/O (detailed)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$disk_device I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "repeat": "disk_device",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\",job=\"$job\",device=\"$disk_device\"}[5m])",
       "legendFormat": "Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\",job=\"$job\",device=\"$disk_device\"}[5m])",
       "legendFormat": "Written bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic (detailed)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$nic Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "repeat": "nic",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~\"$node\",job=\"$job\",device=~\"$nic\"}[5m])",
       "legendFormat": "recv"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~\"$node\",job=\"$job\",device=~\"$nic\"}[5m])",
       "legendFormat": "trans"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic (Packet Rate)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "$nic Traffic (by packets)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
     "repeat": "nic",
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=\"$node\",device=~\"$nic\"}[5m])",
       "legendFormat": "{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{instance=\"$node\",device=~\"$nic\"}[5m])",
       "legendFormat": "{{device}} - Transmit"
      }
     ]
    }
   ]
  }
 ]
}