{
 "title": "PCs Labs",
 "description": "LABs' machines information",
 "tags": [ "labs" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "machines" },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(node_exporter_build_info{job=\"$job\", team=\"rnl-labs\"}, group)"
    }
   },
   {
    "name": "node",
    "label": "Machine",
    "query": {
     "query": "label_values(node_exporter_build_info{job=\"$job\", team=\"rnl-labs\", group=~\"$group\"}, instance)"
    }
   },
   {
    "name": "disk_device",
    "query": {
     "query": "label_values(node_disk_read_bytes_total{job=\"$job\",instance=~\"$node\",device!~\"nbd.*\"}, device)"
    }
   },
   {
    "name": "nic",
    "query": {
     "query": "label_values(node_network_receive_bytes_total{job=\"$job\",instance=~\"$node\"}, device)"
    }
   },
   {
    "name": "hwmon_chip",
    "query": {
     "query": "label_values(node_hwmon_temp_celsius{job=\"$job\",instance=~\"$node\"},chip)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Total Swap",
   "type": "stat",
   "description": "Total Swap",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"}  / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}) * 100)"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Root FS Usage",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"$job\", instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_host_rev{job=\"machines\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\",job=\"$job\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\",job=\"$job\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\",job=\"$job\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  { "title": "Disk Space Usage", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 } },
  {
   "title": "Network Traffic Summary",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    {
     "format": "Bps",
     "label": "Bytes received(-) / transmitted(+)"
    }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$node\",job=\"$job\",device!~\"bond.*|lo\"}[5m]))",
     "legendFormat": "recv"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$node\",job=\"$job\",device!~\"bond.*|lo\"}[5m]))",
     "legendFormat": "trans"
    },
    {
     "expr": "sum(irate(node_network_receive_packets_total{instance=~\"$node\",job=\"$job\",device!~\"bond.*|lo\"}[5m]))",
     "legendFormat": "recv packets"
    },
    {
     "expr": "sum(irate(node_network_transmit_packets_total{instance=~\"$node\",job=\"$job\",device!~\"bond.*|lo\"}[5m]))",
     "legendFormat": "trans packets"
    }
   ]
  },
  {
   "title": "Disks I/O summary",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / written (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=~\"$node\",job=\"$job\",device!~\"md.*\"}[5m]))",
     "legendFormat": "Read bytes"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=~\"$node\",job=\"$job\",device!~\"md.*\"}[5m]))",
     "legendFormat": "Written bytes"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=~\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node\",job=\"$job\"}[5m]))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"$node\",job=\"$job\"}[5m]))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$node\",job=\"$job\"}[5m]))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$node\",job=\"$job\"}[5m]))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node\",job=\"$job\"}[5m]))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",job=\"$job\"}[5m]))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "graph",
   "description": "Entropy available to random number generators",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "node_entropy_available_bits{instance=~\"$node\",job=\"$job\"}",
     "legendFormat": "Available entropy"
    }
   ]
  },
  {
   "title": "Clock skew",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node_timex_offset_seconds{job=\"$job\",instance=~\"$node\"}",
     "legendFormat": "Clock skew"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{instance=\"$node\",phase=\"rtt\"} and on() probe_success{instance=\"$node\"}==1",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum(probe_icmp_duration_seconds{instance=\"$node\",phase=~\"rtt|setup\"}) and on() probe_success{instance=\"$node\"}==1",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Min Negotiated Speed",
   "type": "timeseries",
   "description": "Minimum of negotiated speeds\n(/sys/class/net/e*/speed)",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "min(node_network_speed_bytes{device=~\"e.*\", instance=\"$node\", job=~\"$job\"} * 8) ",
     "legendFormat": "$node"
    }
   ]
  },
  {
   "title": "SSH Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ssh_success{instance=~\"$node.*\", module=\"root\"}",
     "legendFormat": "public key"
    },
    {
     "expr": "ssh_success{instance=~\"$node.*\", module=\"test\"}",
     "legendFormat": "password"
    }
   ]
  },
  {
   "title": "I/O (detailed)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  { "title": "$disk_device I/O", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Network Traffic (detailed)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  { "title": "$nic Traffic", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 } },
  {
   "title": "$nic Traffic (by packets)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
   "repeat": "nic",
   "yaxes": [
    { "format": "pps", "label": "Packets out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=~\"$node\",job=\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=~\"$node\",job=\"$job\",device=~\"$nic\"}[5m])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Thermals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$hwmon_chip Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "repeat": "hwmon_chip",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{job=\"$job\", instance=\"$node\", chip=\"$hwmon_chip\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(node_hwmon_temp_crit_celsius{job=\"$job\", instance=\"$node\", chip=\"$hwmon_chip\"})",
     "legendFormat": "critical"
    },
    {
     "expr": "node_hwmon_temp_celsius{job=\"$job\", instance=\"$node\", chip=\"$hwmon_chip\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}