{
 "title": "Temperatura Ambiente",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "LAB 0",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "iemStatusProbeCurrentTemp{iemStatusProbeNumber=\"1\", instance=\"voltorb\", job=\"snmp-energy-ups\"}"
    }
   ]
  },
  {
   "title": "Admin",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "iemStatusProbeCurrentTemp{iemStatusProbeNumber=\"2\", instance=\"voltorb\", job=\"snmp-energy-ups\"}"
    }
   ]
  },
  {
   "title": "Bastidor C",
   "type": "timeseries",
   "description": "corredor piso 2",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "iemStatusProbeCurrentTemp{iemStatusProbeNumber=\"1\", instance=\"electrode\", job=\"snmp-energy-ups\"}"
    }
   ]
  }
 ]
}