{
 "title": "Labswatch",
 "tags": [ "labs" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "lab",
    "label": "Lab",
    "query": {
     "query": "label_values(node_exporter_build_info{team=\"rnl-labs\"}, group)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Offline",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(min((count(probe_success{team=\"rnl-labs\"}) by (job,group)) - (sum(round(avg_over_time(probe_success{team=\"rnl-labs\"}[1m]), 1)) by (job,group))) by (group))",
     "legendFormat": "Offline hosts"
    }
   ]
  },
  {
   "title": "Linux",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(abs(probe_icmp_reply_hop_limit{team=\"rnl-labs\", group=~\"$lab\", job=\"ping4\"} - 64) < 5) or vector(0)",
     "legendFormat": "Linux hosts"
    }
   ]
  },
  {
   "title": "Windows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(abs(probe_icmp_reply_hop_limit{team=\"rnl-labs\", group=~\"$lab\", job=\"ping4\"} - 128) < 5) or vector(0)",
     "legendFormat": "Windows hosts"
    }
   ]
  },
  {
   "title": "Rescue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(abs(probe_icmp_reply_hop_limit{team=\"rnl-labs\", group=~\"$lab\", job=\"ping4\"} - 32) < 5) or vector(0)",
     "legendFormat": "Rescue"
    }
   ]
  },
  { "title": "Labs Offline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "${lab}",
   "type": "stat",
   "description": "Lab",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "repeat": "lab",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min((count(probe_success{team=\"rnl-labs\", group=~\"$lab\"}) by (job)) - (sum(round(avg_over_time(probe_success{team=\"rnl-labs\", group=~\"$lab\"}[1m]), 1)) by (job)))",
     "legendFormat": "Offline computers"
    }
   ]
  },
  { "title": "Computers status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "$lab",
   "type": "stat",
   "description": "Laboratory status",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "repeat": "lab",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"labs-amt\", group=\"$lab\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "probe_success{job=\"labs-amt\", group=\"$lab\"} + on(instance) probe_icmp_reply_hop_limit{job=\"ping4\", group=~\"$lab\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}