{
 "title": "Website Status",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "http_job", "label": "http_job", "query": "http" },
   { "name": "icmp_job", "label": "icmp_job", "query": "ping4" },
   {
    "name": "target",
    "label": "host",
    "query": {
     "query": "label_values(probe_http_version{job=\"$http_job\"}, instance)"
    }
   },
   {
    "name": "url",
    "label": "url",
    "query": {
     "query": "label_values(probe_http_version{job=\"$http_job\", instance=\"$target\"}, endpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP status code",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"$target\", endpoint=\"$url\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=\"$target\", endpoint=\"$url\"}"
    }
   ]
  },
  {
   "title": "Certificate validity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(probe_ssl_earliest_cert_expiry{instance=\"$target\", endpoint=\"$url\"} - time()) / (60*60*24)"
    }
   ]
  },
  {
   "title": "TLS version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_tls_version_info{instance=\"$target\", endpoint=\"$url\"}"
    }
   ]
  },
  {
   "title": "DNS lookup time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{instance=\"$target\", endpoint=\"$url\",job=\"$http_job\"}"
    }
   ]
  },
  {
   "title": "HTTP version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=\"$target\", endpoint=\"$url\"}"
    }
   ]
  },
  {
   "title": "Redirect(s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_redirects{instance=\"$target\", endpoint=\"$url\"}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"$http_job\", endpoint=\"$url\", instance=\"$target\"}[$__interval]) * 100"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"$http_job\",instance=\"$target\", endpoint=\"$url\"}[$__interval]) * 100"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"$http_job\",instance=\"$target\", endpoint=\"$url\"}[$__interval]) * 100"
    }
   ]
  },
  {
   "title": "HTTP probe duration / status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"$target\", endpoint=\"$url\", job=\"$http_job\"}",
     "legendFormat": "duration"
    },
    {
     "expr": "probe_http_status_code{instance=\"$target\", endpoint=\"$url\"} == 200",
     "legendFormat": "status code"
    },
    {
     "expr": "probe_http_status_code{instance=\"$target\", endpoint=\"$url\"} != 200",
     "legendFormat": "invalid status code"
    }
   ]
  },
  {
   "title": "ICMP probe duration / failure",
   "type": "graph",
   "description": "Display only ICMP failures",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{instance=\"$target\", job=\"$icmp_job\"})",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "HTTP probe (by phase)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"$target\", endpoint=\"$url\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "ICMP probe (by phase)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{instance=\"$target\", job=\"ping4\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  }
 ]
}