{
 "title": "Cluster",
 "description": "slurm-exporter",
 "tags": [ "Slurm" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Cluster Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "slurm_nodes_alloc + slurm_nodes_comp",
     "legendFormat": "Allocated Nodes (including compl)"
    },
    { "expr": "slurm_nodes_mix", "legendFormat": "Mixed Nodes" },
    { "expr": "slurm_nodes_idle", "legendFormat": "Idle Nodes" },
    {
     "expr": "slurm_nodes_alloc + slurm_nodes_down + slurm_nodes_drain + slurm_nodes_idle + slurm_nodes_mix + slurm_nodes_comp + slurm_nodes_maint + slurm_nodes_resv",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Fail/Down/Drain/Err Nodes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_nodes_down", "legendFormat": "Down Nodes" },
    { "expr": "slurm_nodes_drain", "legendFormat": "Draining Nodes" },
    { "expr": "slurm_nodes_err != 0", "legendFormat": "Nodes in *error* state" },
    { "expr": "slurm_nodes_fail != 0", "legendFormat": "Nodes in *fail* state" }
   ]
  },
  {
   "title": "SLURM Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RUNNING/COMPL/PEND Jobs",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_queue_completing != 0", "legendFormat": "Completing Jobs" },
    { "expr": "slurm_queue_running", "legendFormat": "Running Jobs" },
    { "expr": "slurm_queue_pending", "legendFormat": "Pending Jobs" },
    { "expr": "slurm_queue_completed != 0", "legendFormat": "Completed Jobs" }
   ]
  },
  {
   "title": "FAIL/SUSP/CANC/PREEMPT/TIMEDOUT Jobs",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_queue_timeout", "legendFormat": "Timed out Jobs" },
    { "expr": "slurm_queue_failed", "legendFormat": "Failed Jobs" },
    { "expr": "slurm_queue_node_fail", "legendFormat": "Failed jobs (due to NodeFail)" },
    { "expr": "slurm_queue_suspended", "legendFormat": "Suspended Jobs" },
    { "expr": "slurm_queue_cancelled", "legendFormat": "Cancelled Jobs" },
    { "expr": "slurm_queue_preempted", "legendFormat": "Preempted Jobs" }
   ]
  },
  {
   "title": "Users and Accounts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Jobs per Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_user_jobs_running", "legendFormat": "{{user}}" }
   ]
  },
  {
   "title": "Pending Jobs per Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_user_jobs_pending != 0", "legendFormat": "{{user}}" }
   ]
  },
  {
   "title": "Utilized CPUs per user",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 5, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_user_cpus_running > 0", "legendFormat": "{{user}}" }
   ]
  },
  {
   "title": "CPU cores allocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Allocation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "slurm_cpus_total", "legendFormat": "Total number of CPU cores" },
    { "expr": "slurm_cpus_alloc", "legendFormat": "Allocated CPU cores" }
   ]
  },
  {
   "title": "SLURM Scheduler Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Slurm Scheduler Threads",
     "type": "stat",
     "description": "The number of current active slurmctld threads.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "slurm_scheduler_threads", "legendFormat": "Slurm Scheduler Threads" }
     ]
    },
    {
     "title": "Agent Queue Size",
     "type": "stat",
     "description": "The agent mechanism helps to control communication between the Slrum daemons and the controller for a best effort.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "slurm_scheduler_queue_size", "legendFormat": "Agent Queue Size" }
     ]
    },
    {
     "title": "DBD Agent Queue Length",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "slurm_scheduler_dbd_queue_size", "legendFormat": "DBD Agent Queue length" }
     ]
    }
   ]
  },
  {
   "title": "SLURM Scheduler Cycles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Scheduler Cycles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      { "expr": "slurm_scheduler_last_cycle", "legendFormat": "Scheduler Last Cycle Time" },
      { "expr": "slurm_scheduler_mean_cycle", "legendFormat": "Scheduler Mean Cycle Time" }
     ]
    },
    {
     "title": "Backfill Scheduler Cycles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "slurm_scheduler_backfill_last_cycle",
       "legendFormat": "Scheduler Backfill Last Cycle"
      },
      {
       "expr": "slurm_scheduler_backfill_mean_cycle",
       "legendFormat": "Scheduler Backfill Mean Cycle"
      }
     ]
    },
    {
     "title": "Scheduler Backfill Depth Mean",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "slurm_scheduler_backfill_depth_mean",
       "legendFormat": "Mean of processed jobs during backfilling scheduling cycles"
      }
     ]
    },
    {
     "title": " Total backfilled heterogeneous Job components",
     "type": "gauge",
     "description": "Number of heterogeneous job components started thanks to backfilling since last Slurm start",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "slurm_scheduler_backfilled_heterogeneous_total",
       "legendFormat": "Heterogeneous job components"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Backfilled Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Backfilled Jobs (since last slurm start)",
     "type": "graph",
     "description": "Number of jobs started thanks to backfilling since last Slurm start.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(slurm_scheduler_backfilled_jobs_since_start_total[10m])",
       "legendFormat": "DELTA: Total number Backfilled Jobs (since last Slurm start)"
      },
      {
       "expr": "slurm_scheduler_backfilled_jobs_since_start_total",
       "legendFormat": "Total number Backfilled Jobs (since last Slurm start)"
      }
     ]
    },
    {
     "title": "Total Backfilled Jobs (since last stats cycle start)",
     "type": "graph",
     "description": "Number of jobs started thanks to backfilling since last time stats where reset",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "slurm_scheduler_backfilled_jobs_since_cycle_total",
       "legendFormat": " Total Backfilled Jobs (since last stats cycle start)"
      },
      {
       "expr": "delta(slurm_scheduler_backfilled_jobs_since_cycle_total[10m])",
       "legendFormat": "DELTA:  Total Backfilled Jobs (since last stats cycle start)"
      }
     ]
    }
   ]
  }
 ]
}