{
 "title": "S.M.A.R.T Dashboard",
 "description": "Dashboard for viewing detailed disk information based on S.M.A.R.T data",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon",
  "SPN"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(smartmon_smartctl_version, instance) "
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(smartmon_device_info, disk)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "【 General 】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Drives Monitored",
   "type": "stat",
   "description": "É de notar que isto se parte quando mais que uma instance está selecionada :D (funciona com all tho)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartmon_device_active{instance=\"$instance\"}) or sum(smartmon_device_active{})"
    }
   ]
  },
  {
   "title": "Disk Drives List",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(smartmon_device_info{ instance=~\"$instance\", disk=~\"$disk\" }, \"instance\", \"$1\", \"instance\", \"([^:]+).*\")"
    }
   ]
  },
  {
   "title": "Unhealthy Disks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(smartmon_device_smart_healthy{instance=~\"$instance\"})-sum(smartmon_device_smart_healthy{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "【 Temperature 】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature History",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg(smartmon_temperature_celsius_raw_value{ instance=~\"$instance\", disk=~\"$disk\" }) by (instance, disk, name), \"instance\", \"$1\", \"instance\", \"([^.]+).*\")",
     "legendFormat": "【{{instance}}】 {{disk}} {{name}}"
    }
   ]
  },
  {
   "title": "Temperature Bar",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(label_replace(smartmon_temperature_celsius_raw_value{ instance=~\"$instance\", disk=~\"$disk\" }, \"instance\", \"$1\", \"instance\", \"([^.]+).*\"), \"disk\", \"$1\", \"disk\", \"/dev/(.*)\")",
     "legendFormat": "{{instance}}: {{disk}}"
    }
   ]
  },
  {
   "title": "【 Wear and Tear 】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Power On Hours",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(smartmon_power_on_hours_raw_value{ disk=~\"$disk\", instance=~\"$instance\" }, \"instance\", \"$1\", \"instance\", \"([^.]+).*\")",
     "legendFormat": "{{name}} 【{{instance}} {{disk}}】"
    }
   ]
  },
  {
   "title": "Start Stop Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(smartmon_start_stop_count_raw_value { instance=~\"$instance\", disk=~\"$disk\" }, \"instance\", \"$1\", \"instance\", \"([^.]+).*\")",
     "legendFormat": "{{name}} 【{{instance}} {{disk}}】"
    }
   ]
  },
  {
   "title": "Power Cycle Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(smartmon_power_cycle_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}, \"instance\", \"$1\", \"instance\", \"([^.]+).*\")",
     "legendFormat": "{{name}} 【{{instance}} {{disk}}】"
    }
   ]
  },
  {
   "title": "Load Cycle Count",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(smartmon_load_cycle_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}, \"instance\", \"$1\", \"instance\", \"([^.]+).*\")",
     "legendFormat": "{{name}} 【{{instance}} {{disk}}】"
    }
   ]
  },
  {
   "title": "Spin Up Time",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(smartmon_spin_up_time_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}, \"instance\", \"$1\", \"instance\", \"([^.]+).*\")",
     "legendFormat": "{{name}} 【{{instance}} {{disk}}】"
    }
   ]
  },
  {
   "title": "【 Errors 】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Raw Read Error",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(smartmon_raw_read_error_rate_raw_value{ instance=~\"$instance\", disk=~\"$disk\" }, \"instance\", \"$1\", \"instance\", \"([^.]+).*\")",
     "legendFormat": "{{name}} 【{{instance}} {{disk}}】"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "graph",
   "description": "Aggregated graph for all types of errors",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(smartmon_reallocate_nand_blk_cnt_raw_value{ instance=~\"$instance\", disk=~\"$disk\" })",
     "legendFormat": "reallocate_nand_blk_cnt"
    },
    {
     "expr": "sum( smartmon_reallocated_sector_ct_raw_value{ instance=~\"$instance\", disk=~\"$disk\" })",
     "legendFormat": "reallocated_sector_ct"
    },
    {
     "expr": "sum( smartmon_reallocated_event_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\" })",
     "legendFormat": "reallocated_event_count"
    },
    {
     "expr": "sum(smartmon_raw_read_error_rate_raw_value{ instance=~\"$instance\", disk=~\"$disk\" })",
     "legendFormat": "raw_read_error_rate"
    },
    {
     "expr": "sum(smartmon_current_pending_sector_raw_value{ instance=~\"$instance\", disk=~\"$disk\" })",
     "legendFormat": "current_pending_sector"
    },
    {
     "expr": "sum(smartmon_offline_uncorrectable_raw_value{ instance=~\"$instance\", disk=~\"$disk\" })",
     "legendFormat": "offline_uncorrectable"
    },
    {
     "expr": "sum(smartmon_udma_crc_error_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\" })",
     "legendFormat": "udma_crc_error_count"
    },
    {
     "expr": "sum(smartmon_seek_error_rate_raw_value{ instance=~\"$instance\", disk=~\"$disk\" })",
     "legendFormat": "seek_error_rate"
    },
    {
     "expr": "sum(smartmon_spin_retry_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\" })",
     "legendFormat": "spin_retry_count"
    },
    {
     "expr": "sum(smartmon_multi_zone_error_rate_raw_value{ instance=~\"$instance\", disk=~\"$disk\" })",
     "legendFormat": "multi_zone_error_rate_raw_value"
    }
   ]
  },
  {
   "title": "UDMA CRC Error",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(smartmon_udma_crc_error_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\" }, \"instance\", \"$1\", \"instance\", \"([^.]+).*\")",
     "legendFormat": "{{name}} 【{{instance}} {{disk}}】"
    }
   ]
  },
  {
   "title": "Seek Error Rate",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace(smartmon_seek_error_rate_raw_value{ instance=~\"$instance\", disk=~\"$disk\" }, \"instance\", \"$1\", \"instance\", \"([^.]+).*\")",
     "legendFormat": "{{name}} 【{{instance}} {{disk}}】"
    }
   ]
  }
 ]
}