{
 "title": "Switches",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "snmp-network-sw" },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(ifInOctets{job=\"$job\"}, location)"
    }
   },
   {
    "name": "Device",
    "query": {
     "query": "label_values(ifInOctets{job=\"$job\", location=~\"$location\"}, instance)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "label_values(ifInOctets{job=\"$job\",instance=\"$Device\"}, ifAlias)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job=\"$job\",instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "# Up Physical Interfaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(count(ifOperStatus{job=\"$job\",instance=\"$Device\",ifName=~\"1/.*\"} == 1) or vector(0)) + (count(ifOperStatus{job=\"$job\",instance=\"$Device\",ifDescr=~\"AT-9000.*\"} == 1) or vector(0))"
    }
   ]
  },
  {
   "title": "# Unknown Status Interfaces",
   "type": "stat",
   "description": "everything that is not up/down. includes testing and vendor-specific stuff",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ifOperStatus{job=\"$job\",instance=\"$Device\"} != 1 != 2) or vector(0)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "chasHardwareBoardTemp{job=\"$job\", instance=\"$Device\"}",
     "legendFormat": "Board"
    },
    {
     "expr": "chasHardwareCpuTemp{job=\"$job\", instance=\"$Device\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "snmp_scrape_duration_seconds{job=\"$job\",instance=\"$Device\"}",
     "legendFormat": "Scrape duration"
    }
   ]
  },
  {
   "title": "Combined Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{job='$job',instance='$Device'}[5m]) or irate(ifInOctets{job='$job',instance='$Device'}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=\"$job\", instance=\"$Device\"}[5m]) or irate(ifOutOctets{job=\"$job\", instance=\"$Device\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Combined Packet Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(ifHCInUcastPkts{job=\"$job\", instance=\"$Device\"}[5m]) or irate(ifInUcastPkts{job=\"$job\", instance=\"$Device\"}[5m]))",
     "legendFormat": "Unicast In"
    },
    {
     "expr": "sum(irate(ifHCOutUcastPkts{job=\"$job\", instance=\"$Device\"}[5m]) or irate(ifOutUcastPkts{job=\"$job\", instance=\"$Device\"}[5m]))",
     "legendFormat": "Unicast Out"
    },
    {
     "expr": "sum(irate(ifHCInMulticastPktsPkts{job=\"$job\", instance=\"$Device\"}[5m]) or irate(ifInMulticastPkts{job=\"$job\", instance=\"$Device\"}[5m]))",
     "legendFormat": "Multicast In"
    },
    {
     "expr": "sum(irate(ifHCOutMulticastPkts{job=\"$job\", instance=\"$Device\"}[5m]) or irate(ifOutMulticastPkts{job=\"$job\", instance=\"$Device\"}[5m]))",
     "legendFormat": "Multicast Out"
    },
    {
     "expr": "sum(irate(ifHCInBroadcastPkts{job=\"$job\", instance=\"$Device\"}[5m]) or irate(ifInBroadcastPkts{job=\"$job\", instance=\"$Device\"}[5m]))",
     "legendFormat": "Broadcast In"
    },
    {
     "expr": "sum(irate(ifHCOutBroadcastPkts{job=\"$job\", instance=\"$Device\"}[5m]) or irate(ifOutBroadcastPkts{job=\"$job\", instance=\"$Device\"}[5m]))",
     "legendFormat": "Broadcast Out"
    }
   ]
  },
  {
   "title": "Packet traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Interface Packet Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 21 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInUcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=\"$Interface\"}[5m]) or irate(ifInUcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=\"$Interface\"}[5m])",
     "legendFormat": "Unicast In"
    },
    {
     "expr": "irate(ifHCOutUcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[5m]) or irate(ifOutUcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[5m])",
     "legendFormat": "Unicast Out"
    },
    {
     "expr": "irate(ifHCInMulticastPktsPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[5m]) or irate(ifInMulticastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[5m])",
     "legendFormat": "Multicast In"
    },
    {
     "expr": "irate(ifHCOutMulticastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[5m]) or irate(ifOutMulticastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[5m])",
     "legendFormat": "Multicast Out"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[5m]) or irate(ifInBroadcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[5m])",
     "legendFormat": "Broadcast In"
    },
    {
     "expr": "irate(ifHCOutBroadcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[5m]) or irate(ifOutBroadcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[5m])",
     "legendFormat": "Broadcast Out"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 82 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job='$job',instance='$Device',ifAlias='$Interface'}[5m]) or irate(ifInOctets{job='$job',instance='$Device',ifAlias='$Interface'}[5m])",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifHCOutOctets{job='$job',instance='$Device',ifAlias='$Interface'}[5m]) or irate(ifOutOctets{job='$job',instance='$Device',ifAlias='$Interface'}[5m])",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}