{
 "title": "Home Test Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Labs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Offline",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(min((count(probe_success{team=\"rnl-labs\", group!=\"lab0\"}) by (job,group)) - (sum(round(avg_over_time(probe_success{team=\"rnl-labs\"}[1m]), 1)) by (job,group))) by (group))",
     "legendFormat": "Offline hosts"
    }
   ]
  },
  {
   "title": "Linux",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(abs(probe_icmp_reply_hop_limit{team=\"rnl-labs\", group!=\"lab0\", job=\"ping4\"} - 64) < 5) or vector(0)",
     "legendFormat": "Linux hosts"
    }
   ]
  },
  {
   "title": "Windows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(abs(probe_icmp_reply_hop_limit{team=\"rnl-labs\", group!=\"lab0\", job=\"ping4\"} - 128) < 5) or vector(0)",
     "legendFormat": "Windows hosts"
    }
   ]
  },
  {
   "title": "Rescue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(abs(probe_icmp_reply_hop_limit{team=\"rnl-labs\", group!=\"lab0\", job=\"ping4\"} - 32) < 5) or vector(0)",
     "legendFormat": "Rescue"
    }
   ]
  },
  {
   "title": "Offline Labs",
   "type": "stat",
   "description": "Laboratory status",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(probe_success{job=\"labs-amt\", group!=\"lab0\"}) == 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "((probe_success{job=\"labs-amt\", team=\"rnl-labs\"} + on(instance) probe_icmp_reply_hop_limit{job=\"ping4\", team=\"rnl-labs\"}) % 64) != 0",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}