{
 "title": "Routers",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "job", "query": "snmp-network-zeus" },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(ifInOctets{job=\"$job\"}, location)"
    }
   },
   {
    "name": "Device",
    "query": {
     "query": "label_values(ifInOctets{job=\"$job\", location=~\"$location\"}, instance)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "label_values(ifInOctets{job=\"$job\",instance=\"$Device\", ifName=~\"(ge-[05]/0/[02-8])|(reth.*)\"}, ifAlias)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job=\"$job\",instance=\"$Device\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "jnxOperatingTemp{job=\"$job\", instance=\"$Device\", jnxOperatingContentsIndex=\"9\", jnxOperatingL1Index=\"1\",jnxOperatingL2Index=\"0\"}",
     "legendFormat": "Alpha Temp"
    },
    {
     "expr": "jnxOperatingTemp{job=\"$job\", instance=\"$Device\", jnxOperatingContentsIndex=\"9\", jnxOperatingL1Index=\"2\",jnxOperatingL2Index=\"0\"}",
     "legendFormat": "Omega Temp"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "snmp_scrape_duration_seconds{job=\"$job\",instance=\"$Device\"}",
     "legendFormat": "Scrape duration"
    }
   ]
  },
  {
   "title": "Combined Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(ifHCInOctets{job='$job',instance='$Device'}[15m]) or irate(ifInOctets{job='$job',instance='$Device'}[15m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(ifHCOutOctets{job=\"$job\", instance=\"$Device\"}[15m]) or irate(ifOutOctets{job=\"$job\", instance=\"$Device\"}[15m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Combined Packet Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(ifHCInUcastPkts{job=\"$job\", instance=\"$Device\"}[15m]) or irate(ifInUcastPkts{job=\"$job\", instance=\"$Device\"}[15m]))",
     "legendFormat": "Unicast In"
    },
    {
     "expr": "sum(irate(ifHCOutUcastPkts{job=\"$job\", instance=\"$Device\"}[15m]) or irate(ifOutUcastPkts{job=\"$job\", instance=\"$Device\"}[15m]))",
     "legendFormat": "Unicast Out"
    },
    {
     "expr": "sum(irate(ifHCInMulticastPktsPkts{job=\"$job\", instance=\"$Device\"}[15m]) or irate(ifInMulticastPkts{job=\"$job\", instance=\"$Device\"}[15m]))",
     "legendFormat": "Multicast In"
    },
    {
     "expr": "sum(irate(ifHCOutMulticastPkts{job=\"$job\", instance=\"$Device\"}[15m]) or irate(ifOutMulticastPkts{job=\"$job\", instance=\"$Device\"}[15m]))",
     "legendFormat": "Multicast Out"
    },
    {
     "expr": "sum(irate(ifHCInBroadcastPkts{job=\"$job\", instance=\"$Device\"}[15m]) or irate(ifInBroadcastPkts{job=\"$job\", instance=\"$Device\"}[15m]))",
     "legendFormat": "Broadcast In"
    },
    {
     "expr": "sum(irate(ifHCOutBroadcastPkts{job=\"$job\", instance=\"$Device\"}[15m]) or irate(ifOutBroadcastPkts{job=\"$job\", instance=\"$Device\"}[15m]))",
     "legendFormat": "Broadcast Out"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jnxOperatingCPU{job=\"$job\", instance=\"$Device\", jnxOperatingContentsIndex=\"9\", jnxOperatingL1Index=\"1\",jnxOperatingL2Index=\"0\"}",
     "legendFormat": "Alpha"
    },
    {
     "expr": "jnxOperatingCPU{job=\"$job\", instance=\"$Device\", jnxOperatingContentsIndex=\"9\", jnxOperatingL1Index=\"2\",jnxOperatingL2Index=\"0\"}",
     "legendFormat": "Omega"
    }
   ]
  },
  {
   "title": "Number of Flow sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "jnxJsSPUMonitoringCurrentFlowSession{job=\"$job\", instance=\"$Device\"}",
     "legendFormat": "SPU Index {{jnxJsSPUMonitoringIndex}}"
    }
   ]
  },
  {
   "title": "Interface Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{job=\"$job\", instance=\"$Device\", ifName=~\"ge-0/0/[02-8].*\"}",
     "legendFormat": "{{ifName}}"
    }
   ]
  },
  {
   "title": "Packet traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Interface Packet Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 36 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(ifHCInUcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=\"$Interface\"}[15m]) or irate(ifInUcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=\"$Interface\"}[15m])",
     "legendFormat": "Unicast In"
    },
    {
     "expr": "irate(ifHCOutUcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[15m]) or irate(ifOutUcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[15m])",
     "legendFormat": "Unicast Out"
    },
    {
     "expr": "irate(ifHCInMulticastPktsPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[15m]) or irate(ifInMulticastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[15m])",
     "legendFormat": "Multicast In"
    },
    {
     "expr": "irate(ifHCOutMulticastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[15m]) or irate(ifOutMulticastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[15m])",
     "legendFormat": "Multicast Out"
    },
    {
     "expr": "irate(ifHCInBroadcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[15m]) or irate(ifInBroadcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[15m])",
     "legendFormat": "Broadcast In"
    },
    {
     "expr": "irate(ifHCOutBroadcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[15m]) or irate(ifOutBroadcastPkts{job=\"$job\", instance=\"$Device\", ifAlias=~\"$Interface\"}[15m])",
     "legendFormat": "Broadcast Out"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$Interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 67 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job='$job',instance='$Device',ifAlias='$Interface'}[20m]) or irate(ifInOctets{job='$job',instance='$Device',ifAlias='$Interface'}[20m])",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifHCOutOctets{job='$job',instance='$Device',ifAlias='$Interface'}[20m]) or irate(ifOutOctets{job='$job',instance='$Device',ifAlias='$Interface'}[20m])",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}