# Autogenerated by compose2nix
{
  pkgs,
  lib,
  config,
  ...
}:

{
  age.secrets.wordpress-env-file = {
    file = ../../secrets/dei-wordpress-env-file.env.age;
    owner = "docker";
    path = "/etc/wordpress.env";
  };
  age.secrets.wordpress-db-env-file = {
    file = ../../secrets/dei-wordpress-db-env-file.env.age;
    owner = "docker";
    path = "/etc/wordpress-db.env";
  };
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };
  services.nginx.virtualHosts."dei-tas.dei.rnl.tecnico.ulisboa.pt" = {
    serverName = "dei-tas.dei.rnl.tecnico.ulisboa.pt";
    enableACME = true;
    forceSSL = true;
    locations."/" = {
      proxyPass = "http://[::1]:3129";
    };
  };
  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."wordpress-db" = {
    image = "mysql:8.0";
    environmentFiles = [
      /etc/wordpress-db.env
    ];
    environment = {
      "MYSQL_DATABASE" = "exampledb";
      "MYSQL_PASSWORD" = "examplepass";
      "MYSQL_RANDOM_ROOT_PASSWORD" = "1";
      "MYSQL_USER" = "exampleuser";
    };
    volumes = [
      "wordpress_db:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=wordpress_default"
    ];
  };
  systemd.services."podman-wordpress-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-wordpress_default.service"
      "podman-volume-wordpress_db.service"
    ];
    requires = [
      "podman-network-wordpress_default.service"
      "podman-volume-wordpress_db.service"
    ];
    partOf = [
      "podman-compose-wordpress-root.target"
    ];
    wantedBy = [
      "podman-compose-wordpress-root.target"
    ];
  };
  virtualisation.oci-containers.containers."wordpress-wordpress" = {
    image = "wordpress";
    environmentFiles = [
      /etc/wordpress.env
    ];
    environment = {
      "WORDPRESS_DB_HOST" = "db";
      "WORDPRESS_DB_NAME" = "exampledb";
      "WORDPRESS_DB_PASSWORD" = "examplepass";
      "WORDPRESS_DB_USER" = "exampleuser";
    };
    volumes = [
      "wordpress_wordpress:/var/www/html:rw"
    ];
    ports = [
      "3129:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wordpress"
      "--network=wordpress_default"
    ];
  };
  systemd.services."podman-wordpress-wordpress" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-wordpress_default.service"
      "podman-volume-wordpress_wordpress.service"
    ];
    requires = [
      "podman-network-wordpress_default.service"
      "podman-volume-wordpress_wordpress.service"
    ];
    partOf = [
      "podman-compose-wordpress-root.target"
    ];
    wantedBy = [
      "podman-compose-wordpress-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-wordpress_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f wordpress_default";
    };
    script = ''
      podman network inspect wordpress_default || podman network create wordpress_default
    '';
    partOf = [ "podman-compose-wordpress-root.target" ];
    wantedBy = [ "podman-compose-wordpress-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-wordpress_db" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect wordpress_db || podman volume create wordpress_db
    '';
    partOf = [ "podman-compose-wordpress-root.target" ];
    wantedBy = [ "podman-compose-wordpress-root.target" ];
  };
  systemd.services."podman-volume-wordpress_wordpress" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect wordpress_wordpress || podman volume create wordpress_wordpress
    '';
    partOf = [ "podman-compose-wordpress-root.target" ];
    wantedBy = [ "podman-compose-wordpress-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-wordpress-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
