# Autogenerated by compose2nix
{
  pkgs,
  lib,
  ...
}:

{
  # Runtime
  age.secrets.wordpress-env-file = {
    file = ../../secrets/dei-wordpress-env-file.env.age;
    path = "/etc/wordpress.env";
  };
  age.secrets.wordpress-db-env-file = {
    file = ../../secrets/dei-wordpress-db-env-file.env.age;
    path = "/etc/wordpress-db.env";
  };
  services.nginx.virtualHosts."dei-tas.tecnico.ulisboa.pt" = {
    serverName = "dei-tas.blatta.rnl.tecnico.ulisboa.pt";
    enableACME = true;
    forceSSL = true;
    locations."/" = {
      proxyPass = "http://[::1]:3129";
    };
  };
  # Containers
  virtualisation.oci-containers.containers."wordpress-db" = {
    image = "mysql:8.0";
    environmentFiles = [
      /etc/wordpress-db.env
    ];

    volumes = [
      "wordpress_db:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=wordpress_default"
    ];
  };
  systemd.services."docker-wordpress-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-wordpress_default.service"
      "docker-volume-wordpress_db.service"
    ];
    requires = [
      "docker-network-wordpress_default.service"
      "docker-volume-wordpress_db.service"
    ];
    partOf = [
      "docker-compose-wordpress-root.target"
    ];
    wantedBy = [
      "docker-compose-wordpress-root.target"
    ];
  };
  virtualisation.oci-containers.containers."wordpress-wordpress" = {
    image = "wordpress";
    environmentFiles = [
      /etc/wordpress.env
    ];

    volumes = [
      "wordpress_wordpress:/var/www/html:rw"
    ];
    ports = [
      "3129:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wordpress"
      "--network=wordpress_default"
    ];
  };
  systemd.services."docker-wordpress-wordpress" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-wordpress_default.service"
      "docker-volume-wordpress_wordpress.service"
    ];
    requires = [
      "docker-network-wordpress_default.service"
      "docker-volume-wordpress_wordpress.service"
    ];
    partOf = [
      "docker-compose-wordpress-root.target"
    ];
    wantedBy = [
      "docker-compose-wordpress-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-wordpress_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f wordpress_default";
    };
    script = ''
      docker network inspect wordpress_default || docker network create wordpress_default
    '';
    partOf = [ "docker-compose-wordpress-root.target" ];
    wantedBy = [ "docker-compose-wordpress-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-wordpress_db" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect wordpress_db || docker volume create wordpress_db
    '';
    partOf = [ "docker-compose-wordpress-root.target" ];
    wantedBy = [ "docker-compose-wordpress-root.target" ];
  };
  systemd.services."docker-volume-wordpress_wordpress" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect wordpress_wordpress || docker volume create wordpress_wordpress
    '';
    partOf = [ "docker-compose-wordpress-root.target" ];
    wantedBy = [ "docker-compose-wordpress-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-wordpress-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
