auths:
  public_v2:
    version: 2
    community: public
  zeus_auth:
    version: 3
    username: ${SNMP_ZEUS_USER}
    password: ${SNMP_ZEUS_PASSWORD}
    security_level: authPriv
    auth_protocol: SHA
    priv_protocol: AES
    priv_password: ${SNMP_ZEUS_PRIV_PASSWORD}

modules:
  network-switch:
    walk:
      - interfaces
      - sysUpTime
      - ifXTable
      - alcatelIND1ChassisMIB # temperatures
    lookups:
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [ifIndex]
        lookup: ifDescr
      - source_indexes: [ifIndex]
        # Use OID to avoid conflict with Netscaler NS-ROOT-MIB.
        lookup: 1.3.6.1.2.1.31.1.1.1.1 # ifName

    overrides:
      ifType:
        type: EnumAsInfo

  network-zeus:
    timeout: 30s # it's a lot of stuff
    walk:
      - interfaces
      - sysUpTime
      - ifXTable

      # JunOS MIBs
      # See MIB Explorer: https://apps.juniper.net/mib-explorer/navigate.jsp
      - jnxAlarms
      - jnxHostResourcesMIB
      - jnxIpv6
      - jnxRpf
      # Number of Flow sessions
      - jnxJsSPUMonitoringCurrentFlowSession
      - jnxOperatingTemp
      - jnxOperatingCPU

    lookups:
      - source_indexes: [ifIndex]
        lookup: ifAlias
      - source_indexes: [ifIndex]
        lookup: ifDescr
      - source_indexes: [ifIndex]
        # Use OID to avoid conflict with Netscaler NS-ROOT-MIB.
        lookup: 1.3.6.1.2.1.31.1.1.1.1 # ifName

    overrides:
      ifType:
        type: EnumAsInfo

  energy-ups:
    walk:
      - sysUpTime
      - interfaces

      # See PowerNet MIB Reference: https://networkupstools.org/protocols/snmp/APC-Powernet.pdf
      # "How to monitor a UPS"
      - upsBattery
      - upsComm
      - upsInput
      - upsOutput

      # Self-test and self-calibration results
      - upsAdvTest

      # UPS Temperature sensors
      - iemStatusProbesTable

      # not in the reference but useful
      - upsOutletGroups
      # - emStatusProbesTable # name makes more sense, but appears to be redundant or useless
    lookups:
      - source_indexes: [upsOutletGroupStatusIndex]
        lookup: upsOutletGroupStatusName
      - source_indexes: [iemStatusProbeIndex]
        lookup: iemStatusProbeName
      - source_indexes: [emStatusProbeIndex]
        lookup: emStatusProbeName
    overrides:
      ifType:
        type: EnumAsInfo
      upsAdvBatteryCondition:
        type: EnumAsStateSet
      upsAdvBatteryChargingCurrentRestricted:
        type: EnumAsStateSet
      upsAdvBatteryChargerStatus:
        type: EnumAsStateSet

  energy-pdu:
    walk:
      - sysUpTime
      - interfaces

      # See: https://oidref.com/1.3.6.1.4.1.318.1.1.12
      # these looked enough
      - rPDUOutletStatusTable
      - rPDUIdent
    lookups:
      - source_indexes: [rPDUOutletStatusIndex]
        lookup: rPDUOutletStatusOutletName
    overrides:
      ifType:
        type: EnumAsInfo
      #rPDUOutletStatusOutletState:
      #  type: EnumAsStateSet
      #rPDUOutletStatusCommandPending:
      #  type: EnumAsStateSet
      #rPDUIdentDeviceOrientation:
      #  type: EnumAsStateSet

